### PR TITLE
Moves configuration delegates to VM as events.

### PR DESCRIPTION
**Pull request by Banane9**

### CODE REVIEW

**Comment by Deijin27** [comment]
You've give the ensureCorrectVm method aggressive inlining attribute. But I recall reading this here
 https://learn.microsoft.com/en-us/windows/communitytoolkit/developer-tools/throwhelper#technical-details

What I take from it is, specifically regarding exceptions, the JIT compiler could potentially create more efficient code with not-inlined exceptions.

**Comment by Banane9** [comment]
> What I take from it is, specifically regarding exceptions, the JIT compiler could potentially create more efficient code with not-inlined exceptions.

Hmmm, that would apply to the throwing of the exception itself, not the check - so the best approach would seem to be, to use the ThrowHelper class instead of manual throwing, or using the Guard API

https://learn.microsoft.com/en-us/windows/communitytoolkit/developer-tools/guard

**Comment by Deijin27** [comment]
That's fine. I just wanted to mention it to find out if you had a reason for using the inlining attribute. 

I dont think we should add depndencies to any other libraries unless absolutely necessary.

**Comment by Banane9** [comment]
It would be possible to have something like this in the repository here too, I suppose?  
The code is licensed under MIT, so free to take.

https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/rel/7.1.0/Microsoft.Toolkit.Diagnostics/ThrowHelper.cs

**Comment by Deijin27** [comment]
If heapSize which is size_t needs to be the nuint, is this also necessary for other instances of size_t? Namely ReallocateInternal, SetSlotBytes, SetSlotNewForeign?

**Comment by Banane9** [comment]
mmm, I suppose so - I think those don't even have tests yet, or it just didn't come up because the important part is in the right place

**Comment by Banane9** [comment]
there we go - for WrenReallocateInternal it doesn't really matter, as the delegate field on the config is just there to match the native one anyways

**Review by Deijin27 — APPROVED** [review]

**Pull request merged**
